export const cardArray = [
  {
    id: 1,
    name: 'Serra Avatar',
    types: ['Creature'],
    incollection: false,
    colors: ['White'],
    date: '2008-04-01',
    imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=376495&type=card',
  },
  {
    id: 2,
    name: 'Clone',
    types: ['Creature'],
    incollection: false,
    colors: ['Blue'],
    date: '2013-07-01',
    imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=99&type=card',
  },
  {
    id: 3,
    name: 'Krenko, Mob Boss',
    types: ['Creature'],
    incollection: false,
    colors: ['Red'],
    date: '2012-07-01',
    imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=489529&type=card',
  },
  {
    id: 4,
    name: 'Savage Stomp',
    types: ['Sorcery'],
    incollection: false,
    colors: ['Green'],
    date: 'No',
    imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=489410&type=card',
  },
  {
    id: 5,
    name: 'Shadowblood Ridge',
    types: ['Land'],
    incollection: false,
    colors: ['Black', 'Red'],
    date: '2015-06-22',
    imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=482937&type=card',
  },
  {
    id: 6,
    name: 'Archangel Avacyn',
    types: ['Creature'],
    incollection: true,
    colors: ['White'],
    date: '2016-04-08',
    imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=409741&type=card',
  },
];
